font-color:
  r: 251
  g: 227
  b: 182
font-effect-color:
  r: 200
  g: 184
  b: 148
background-color:
  r: 50
  g: 50
  b: 50
font-family: "微软雅黑"
refresh-token: ""
musixmatch-token: ""
client-id: ""
client-secret: ""
always-top: true
show-background-when-unlocked: false
show-background-when-locked: false